"""Verify the strength/weakness/blind coverage matrix (code/surr/coverage.yaml) against the problem and learner
registries, and regenerate docs/PROBLEM_MATRIX.md.

Checks
  1. every id in favored_by / hurt_by / blind resolves to a problem, probe family, VLSE category, tag or condition;
  2. every method has >= 1 favouring and >= 1 hurting entry;
  3. every implemented or planned learner appears in the matrix, and every matrix learner exists;
  4. the blind set is non-empty and no method claims a blind entry as favoured;
  5. every probe family is used at least once as a strength *and* once as a weakness case (otherwise it is not
     discriminating anything and should be dropped or re-assigned).
Exit code 1 on any failure.
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "code"))
from surr import learners as Lr, problems as P  # noqa: E402

from surr import acquisitions as _A, multifidelity as _MF, optimizers as _O, samplers as _S, upscalers as _U  # noqa: E402
IMPL = {"learners": set(Lr.REGISTRY), "samplers": set(_S.REGISTRY), "acquisitions": set(_A.REGISTRY),
        "multifidelity": set(_MF.REGISTRY), "upscalers": set(_U.REGISTRY), "optimizers": set(_O.REGISTRY)}
MATRIX = yaml.safe_load((Path(__file__).parent / "coverage.yaml").read_text(encoding="utf8"))
SECTIONS = ["learners", "samplers", "acquisitions", "multifidelity", "upscalers", "optimizers"]


def resolve(i):
    names = set(P.REGISTRY)
    if i in names:
        return "problem"
    if any(n.startswith(i + "_d") for n in names):
        return "probe family"
    if any(p.category == i for p in P.REGISTRY.values()):
        return "VLSE category"
    if i in P.CONDITIONS:
        return "condition"
    if any(i in p.tags for p in P.REGISTRY.values()):
        return "tag"
    return None


def main():
    errors = []
    blind = set(MATRIX["blind"])
    for b in blind:
        if not resolve(b):
            errors.append(f"blind id '{b}' does not resolve")
    fav, hurt = defaultdict(list), defaultdict(list)
    for sec in SECTIONS:
        for m, e in MATRIX[sec].items():
            if not e.get("favored_by"):
                errors.append(f"{sec}/{m}: no favoured case")
            if not e.get("hurt_by"):
                errors.append(f"{sec}/{m}: no hurting case")
            for i in e.get("favored_by", []):
                if not resolve(i):
                    errors.append(f"{sec}/{m}: favoured id '{i}' does not resolve")
                if i in blind:
                    errors.append(f"{sec}/{m}: claims blind '{i}' as favoured")
                fav[i].append(f"{m}")
            for i in e.get("hurt_by", []):
                if not resolve(i):
                    errors.append(f"{sec}/{m}: hurt id '{i}' does not resolve")
                hurt[i].append(f"{m}")
    known = set(Lr.REGISTRY) | set(Lr.PLANNED)
    for m in known - set(MATRIX["learners"]):
        errors.append(f"learner '{m}' is registered but missing from the matrix")
    for m in set(MATRIX["learners"]) - known:
        errors.append(f"matrix learner '{m}' is neither implemented nor planned")
    families = sorted({n.rsplit("_d", 1)[0] for n, p in P.REGISTRY.items() if p.block == "P-FEAT" and "+dummy" not in n})
    non_disc = [f for f in families if f not in blind and not (fav.get(f) and hurt.get(f))]
    write_doc(fav, hurt, blind, families)
    for sec in SECTIONS:
        n_impl = sum(m in IMPL[sec] for m in MATRIX[sec])
        extra = sorted(IMPL[sec] - set(MATRIX[sec]))
        print(f"  {sec:14s} {n_impl:2d} implemented / {len(MATRIX[sec]):2d} in matrix"
              + (f"   (implemented but not in matrix: {extra})" if extra else ""))
    print(f"blind entries: {len(blind)}; probe families: {len(families)}")
    if non_disc:
        print("WARNING probe families not used as both strength and weakness:", non_disc)
    if errors:
        print("FAIL"); [print("  -", e) for e in errors]; sys.exit(1)
    print("coverage OK")


def write_doc(fav, hurt, blind, families):
    L = ["# Problem Matrix — strengths, weaknesses and blind problems",
         "",
         "_Generated by `code/surr/check_coverage.py` from `code/surr/coverage.yaml`; do not edit by hand._",
         "",
         "Every method has at least one problem designed to favour it and one designed to hurt it; blind problems",
         "have no designed winner. These are a-priori expectations frozen before E3 — results may contradict them,",
         "and contradictions are findings.",
         "",
         "## By method", ""]
    for sec in SECTIONS:
        L += [f"### {sec.capitalize()}", "", "| Method | Status | Should win on | Should lose on | Mechanism |",
              "|---|---|---|---|---|"]
        for m, e in MATRIX[sec].items():
            st = "implemented" if m in IMPL[sec] else "planned"
            L.append(f"| `{m}` | {st} | {', '.join(e['favored_by'])} | {', '.join(e['hurt_by'])} | {e.get('why', '')} |")
        L.append("")
    L += ["## By problem", "", "| Problem / condition | Kind | Expected winners | Expected losers |", "|---|---|---|---|"]
    ids = sorted(set(fav) | set(hurt) | set(blind) | set(families))
    for i in ids:
        kind = "**blind**" if i in blind else (resolve(i) or "?")
        L.append(f"| `{i}` | {kind} | {', '.join(sorted(set(fav.get(i, [])))) or '—'} | "
                 f"{', '.join(sorted(set(hurt.get(i, [])))) or '—'} |")
    (ROOT / "docs" / "PROBLEM_MATRIX.md").write_text("\n".join(L) + "\n", encoding="utf8")


if __name__ == "__main__":
    main()
